In [1]:
import pandas as pd
import numpy as np

import re
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split

from  sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
accuracy score
                GaussianNB  MultinomialNB  BernoulliNB
   CountVectorizer 
without_hyper    99 -  64    97 -  81        94 - 78        
by removing      99 - 63     97  - 80        94 - 78
Numerical         
with stopward    does not affect very much
with min_df      80 - 71     84 - 80         83 - 76
TfidfVectorizer  86 - 76     85 - 81         83 - 79

In [ ]:
create data x and y

In [1]:

import os 
import glob

In [2]:
os.getcwd()

'F:\\data science\\PRACTICE\\class projects\\Movie Sentiment analysis'

In [6]:
folder="files\\"
os.listdir(folder)

['.ipynb_checkpoints', 'neg', 'pos']

In [ ]:
movie_reviews\\neg\\

In [7]:
neg_files_path=folder + 'neg'
pos_files_path= folder +'pos'

neg_text_file=glob.glob(f"{neg_files_path}\\*.txt")
pos_text_file=glob.glob(f"{pos_files_path}\\*.txt")

In [8]:
review_list=[]
for file_path in neg_text_file:
    f=open(file_path)
    txtfile=f.read()
    txtfile=re.sub('[^a-zA-Z]+',' ',txtfile)
    f.close()
    review_list.append(txtfile)
    
for file_path in pos_text_file:
    f=open(file_path)
    txtfile=f.read()
    txtfile=re.sub('[^a-zA-Z]+',' ',txtfile)
    f.close()
    review_list.append(txtfile)
    
print(len(review_list))

2000

In [ ]:
we have 2000 row now 
(x)feature to be created

In [29]:
cntv=CountVectorizer(stop_words='english', min_df= 0.05)
x_cntv=cntv.fit_transform(review_list)

x=pd.DataFrame(x_cntv.toarray(),columns=cntv.get_feature_names_out())
x

,ability,able,absolutely,act,acting,action,actor,actors,actress,actual,...,writers,writing,written,wrong,wrote,year,years,yes,york,young
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
3,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,0,0,1,0,0,0,0,0,...,0,1,1,0,0,3,0,0,0,0
1996,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1997,1,0,0,0,0,3,0,0,0,1,...,0,0,0,0,1,0,0,0,0,2
1998,0,0,0,0,0,0,1,2,0,0,...,0,0,0,0,0,1,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [43]:
tfidV=TfidfVectorizer(stop_words='english' , min_df= 0.05)
x_tfidV=tfidV.fit_transform(review_list)

x=pd.DataFrame(x_tfidV.toarray(),columns=tfidV.get_feature_names_out())
x

,ability,able,absolutely,act,acting,action,actor,actors,actress,actual,...,writers,writing,written,wrong,wrote,year,years,yes,york,young
0,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.049035,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.045701,0.0,0.0,0.000000
1,0.00000,0.000000,0.0,0.0,0.164134,0.079639,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
2,0.00000,0.000000,0.0,0.0,0.056017,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.066405,0.068888,0.000000,0.000000,0.000000,0.0,0.0,0.057220
3,0.00000,0.099515,0.0,0.0,0.000000,0.000000,0.000000,0.079786,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.074194,0.000000,0.0,0.0,0.000000
4,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.116082,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.00000,0.000000,0.0,0.0,0.040102,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.059425,0.047539,0.000000,0.000000,0.113246,0.000000,0.0,0.0,0.000000
1996,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.103339,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
1997,0.05055,0.000000,0.0,0.0,0.000000,0.090837,0.000000,0.000000,0.0,0.050657,...,0.0,0.000000,0.000000,0.000000,0.051091,0.000000,0.000000,0.0,0.0,0.063745
1998,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.049242,0.090272,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.041972,0.000000,0.0,0.0,0.000000
1999,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.046050,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000

In [ ]:
create target columns 
nagative reviw =0
positive review =1

In [12]:
positive_target=np.ones(1000,dtype='int')
negative_target=np.zeros(1000,dtype='int')

y=np.append(negative_target,positive_target)
y=pd.Series(y)
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    1
1996    1
1997    1
1998    1
1999    1
Length: 2000, dtype: int32

In [ ]:
model building

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1,stratify=y)

# GaussianNB

In [45]:
Gnb=GaussianNB()
Gnb.fit(x_train,y_train)

GaussianNB()

In [46]:
# Evaluation training
y_pred_train = Gnb.predict(x_train)

print('classification report :', classification_report(y_pred_train,y_train))

print('accuracy score :', accuracy_score(y_pred_train,y_train))

classification report :               precision    recall  f1-score   support

           0       0.88      0.85      0.87       830
           1       0.85      0.88      0.86       770

    accuracy                           0.86      1600
   macro avg       0.86      0.87      0.86      1600
weighted avg       0.87      0.86      0.87      1600

accuracy score : 0.865

In [47]:
# Evaluation testing
y_pred_test = Gnb.predict(x_test)

print('classification report :', classification_report(y_test,y_pred_test))

print('accuracy score :', accuracy_score(y_test,y_pred_test))

classification report :               precision    recall  f1-score   support

           0       0.74      0.81      0.77       200
           1       0.78      0.71      0.75       200

    accuracy                           0.76       400
   macro avg       0.76      0.76      0.76       400
weighted avg       0.76      0.76      0.76       400

accuracy score : 0.7575

# MultinomialNB

In [48]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)

MultinomialNB()

In [49]:
# Evaluation training
y_pred_train = mnb.predict(x_train)

print('classification report :', classification_report(y_pred_train,y_train))

print('accuracy score :', accuracy_score(y_pred_train,y_train))

classification report :               precision    recall  f1-score   support

           0       0.87      0.85      0.86       821
           1       0.84      0.87      0.85       779

    accuracy                           0.86      1600
   macro avg       0.86      0.86      0.86      1600
weighted avg       0.86      0.86      0.86      1600

accuracy score : 0.855625

In [50]:
# Evaluation testing
y_pred_test = mnb.predict(x_test)

print('classification report :', classification_report(y_test,y_pred_test))

print('accuracy score :', accuracy_score(y_test,y_pred_test))

classification report :               precision    recall  f1-score   support

           0       0.80      0.81      0.81       200
           1       0.81      0.80      0.80       200

    accuracy                           0.81       400
   macro avg       0.81      0.80      0.80       400
weighted avg       0.81      0.81      0.80       400

accuracy score : 0.805

# BernoulliNB

In [51]:
bnb=BernoulliNB()
bnb.fit(x_train,y_train)

BernoulliNB()

In [52]:
# Evaluation training
y_pred_train = bnb.predict(x_train)

print('classification report :', classification_report(y_pred_train,y_train))

print('accuracy score :', accuracy_score(y_pred_train,y_train))

classification report :               precision    recall  f1-score   support

           0       0.88      0.80      0.84       877
           1       0.78      0.87      0.82       723

    accuracy                           0.83      1600
   macro avg       0.83      0.83      0.83      1600
weighted avg       0.84      0.83      0.83      1600

accuracy score : 0.830625

In [53]:
# Evaluation testing
y_pred_test = bnb.predict(x_test)

print('classification report :', classification_report(y_test,y_pred_test))

print('accuracy score :', accuracy_score(y_test,y_pred_test))

classification report :               precision    recall  f1-score   support

           0       0.74      0.81      0.78       200
           1       0.79      0.72      0.75       200

    accuracy                           0.77       400
   macro avg       0.77      0.77      0.76       400
weighted avg       0.77      0.77      0.76       400

accuracy score : 0.765